"""Generate the weekly-report cross-validation golden for aura-api — the deploy gate.

aura-api composes the weekly report in-Worker (src/report.ts) from precomputed
daily_guidance rows; engine/reports.py is the source of truth. This script
builds the golden the Worker's CI checks itself against: for each case it
computes the seven days' energies and area scores with the REAL engine
(Swiss Ephemeris + the active score_rules) and the full expected report with
`build_weekly_report` under the ACTIVE report corpus, then writes
aura-api/test/golden/report_crossval.json. test/report.crossval.test.ts replays
every case through the TypeScript implementation and requires byte-agreement on
every field — including `week_index`, whose ABSOLUTE value (not just its slope)
is what caught the Unix-epoch-origin bug recorded in docs/REPORTS.md.

Unlike crossval_dasha.py this script does not shell out to node: the vitest
suite IS the TypeScript half, and it runs on every deploy. Regenerate whenever
engine/reports.py, the active score_rules, or the report corpus changes:

    uv run python scripts/crossval_report.py
"""

from __future__ import annotations

import json
import os
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)))

from engine.content import (  # noqa: E402
    ACTIVE_REPORT_CONTENT_VERSION,
    ACTIVE_SCORE_RULES_VERSION,
)
from engine.daily import build_daily_sky  # noqa: E402
from engine.reports import (  # noqa: E402
    WEEK_DAYS,
    build_weekly_report,
    load_report_content_from_json,
)
from engine.scoring import guidance_for_nakshatra, load_rules_from_json  # noqa: E402

ENGINE_ROOT = Path(__file__).resolve().parent.parent
GOLDEN_PATH = ENGINE_ROOT.parent / "aura-api" / "test" / "golden" / "report_crossval.json"

#: Same span the composition gates sample. 6 natals x 12 weeks = 72 cases —
#: every shape/turn the real sky produces in the span, and enough weeks that
#: the opening rotation is exercised well past a single week.
FIRST_MONDAY = date(2026, 7, 20)
N_WEEKS = 12
NATALS = (0, 3, 7, 13, 20, 26)


def main() -> int:
    rules = load_rules_from_json()
    content = load_report_content_from_json()

    cases = []
    for natal in NATALS:
        for w in range(N_WEEKS):
            monday = FIRST_MONDAY + timedelta(weeks=w)
            days = [monday + timedelta(days=i) for i in range(WEEK_DAYS)]
            skies = [build_daily_sky(d) for d in days]
            guidance = [guidance_for_nakshatra(natal, s, rules) for s in skies]
            input_days = [
                {"date": d.isoformat(), "energy": g["energy"], "scores": g["scores"]}
                for d, g in zip(days, guidance, strict=True)
            ]
            expected = build_weekly_report(natal, monday, rules, content)
            cases.append(
                {
                    "input": {
                        "nakshatra_index": natal,
                        "week_start": monday.isoformat(),
                        "days": input_days,
                    },
                    "expected": expected,
                }
            )

    golden = {
        "_about": (
            "Cross-validation golden for the weekly report. Generated by "
            "aura-engine (scripts/crossval_report.py over engine/reports.py, "
            "the source of truth). The Worker composes reports in TypeScript "
            "from precomputed daily_guidance rows; this file gates that it "
            "agrees exactly. Regenerate whenever engine/reports.py or the "
            "corpus changes."
        ),
        "content_version": ACTIVE_REPORT_CONTENT_VERSION,
        "rules_version": ACTIVE_SCORE_RULES_VERSION,
        "cases": cases,
    }
    GOLDEN_PATH.write_text(json.dumps(golden, indent=1, ensure_ascii=False) + "\n")
    rel = GOLDEN_PATH.relative_to(ENGINE_ROOT.parent)
    print(
        f"golden file written: {rel} ({len(cases)} cases, "
        f"{ACTIVE_REPORT_CONTENT_VERSION} / {ACTIVE_SCORE_RULES_VERSION})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
