"""Cross-validate the Worker's muhurat ranking against this engine — deploy gate.

The binding condition in docs/MUHURAT.md §5: if a ranked, personalised muhurat
becomes app-visible via the Worker, it must ship the lagna through the
already-gated ascendant port and add a golden-parity gate over the RANKING,
engine-vs-Worker, identical in kind to natal/dasha. This script is that gate.

WHAT IS COMPARED, AND WHY IN TWO LAYERS. A muhurat answer is (inputs) →
(ranking): the inputs are the 16 choghadiya slots + 3 kaal starts (already
gated by crossval_window.py to ±90 s) and the rising sign at each slot midpoint
(the ascendant port, already gated to 1'); the ranking is engine/muhurat.py's
`rank_windows`. Because the two sides' rise/set models legitimately differ by
up to ~45 s, a slot midpoint can drift, and near a sign ingress that drift can
flip the midpoint's rising sign — which changes the score and hence the order.
That is a tolerance problem in the INPUTS, not a bug in the RANKING, so:

  layer 1 — END-TO-END: both sides compute the full answer from (place, date,
    purpose, natal lagna). Candidate sets must match by name+time (±90 s),
    personalisation labels must match exactly, and every midpoint rising sign
    must match unless the engine places it within BOUNDARY_DEG of an ingress
    (flagged, counted, must stay rare). On cases with no boundary window the
    full order and every score must match exactly.

  layer 2 — RANK PARITY: the Worker's `rankWindows` is replayed over the
    ENGINE's own windows (Swiss-resolved slots + lagna signs) and must
    reproduce the engine ranking DEEP-EQUAL on every case, boundary or not.
    This pins the ported purpose rules, scores, tie-breaks and the
    impersonal/personal_12way labelling with no tolerance at all.

The engine side composes the same pieces `auspicious_timings` uses — Swiss
rise/set + engine/choghadiya.py (via crossval_window.engine_window, whose
fixed-offset handling is DST-correct) + engine ascendant_sidereal + engine
rank_windows — rather than the IST-convenience wrapper, exactly as
crossval_window.py composes engine pieces.

ETHICS GATES: the muhurat voice corpus (DESCRIPTORS — kaal lines, band lines,
the personalisation honesty lines) is gated at authoring time by
tests/test_muhurat_gates_falsify.py. This script exports that exact corpus into
`aura-api/src/muhuratTables.gen.ts` and embeds it in the golden; the vitest
gate asserts the Worker's served corpus is byte-equal. The Worker composes
lines only from the corpus, so ungated copy cannot ship without failing CI.

On success it (re)writes aura-api/test/golden/muhurat_crossval.json.

Run:  uv run python scripts/crossval_muhurat.py
Exit: non-zero on ANY disagreement (failing cases are printed; do not tune).
"""

from __future__ import annotations

import json
import os
import random
import subprocess
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)))

from engine.chart import ascendant_sidereal  # noqa: E402
from engine.muhurat import DESCRIPTORS, PURPOSES, rank_windows  # noqa: E402
from engine import muhurat as muh  # noqa: E402
from crossval_window import PLACES, engine_window  # noqa: E402

import swisseph as swe  # noqa: E402

ENGINE_ROOT = Path(__file__).resolve().parent.parent
AURA_API = ENGINE_ROOT.parent / "aura-api"
TABLES_PATH = AURA_API / "src" / "muhuratTables.gen.ts"
GOLDEN_PATH = AURA_API / "test" / "golden" / "muhurat_crossval.json"

SEED = 285
N_DATES = 3  # per place, plus the fixed DST-transition cases below
TOLERANCE_S = 90  # the crossval_window rise/set model gap
# Max midpoint drift is TOLERANCE_S; the ascendant rises at up to ~0.5°/min at
# the panel's latitudes, so 90 s ≈ 0.75°. 1.0° of margin means a sign flip
# outside it is a real disagreement, never drift.
BOUNDARY_DEG = 1.0

# DST transitions inside the day/night span — the cases that break wall-clock
# arithmetic (see crossval_window.py's fixed-offset note).
FIXED_CASES = [
    ("Auckland", "2026-04-04"),  # NZ DST ends overnight
    ("London", "2026-03-29"),    # EU DST starts overnight
    ("Pune", "2026-07-22"),      # the launch market, a known date
]

START = datetime(2026, 1, 1)
END = datetime(2026, 12, 31)


def export_tables() -> dict:
    tables = {
        "purposes": {k: sorted(v) for k, v in PURPOSES.items()},
        "chogRank": muh.CHOG_RANK,
        "lagnaClassFit": {k: sorted(v) for k, v in muh.LAGNA_CLASS_FIT.items()},
        "goodLagnaHouse": sorted(muh.GOOD_LAGNA_HOUSE),
        "descriptors": DESCRIPTORS,
    }
    return tables


def write_tables(tables: dict) -> None:
    body = json.dumps(tables, indent=2, ensure_ascii=False)
    TABLES_PATH.write_text(
        "// GENERATED by aura-engine/scripts/crossval_muhurat.py — DO NOT EDIT.\n"
        "//\n"
        "// Single source of truth: aura-engine/engine/muhurat.py. The purpose rules,\n"
        "// scores and the voice corpus (gated by tests/test_muhurat_gates_falsify.py)\n"
        "// are machine-exported from the live Python module. A hand edit here\n"
        "// diverges from the engine and fails test/muhurat.crossval.test.ts.\n"
        "// Regenerate:  uv run python scripts/crossval_muhurat.py\n"
        f"export const MUHURAT = {body};\n"
    )


def generate_cases() -> list[dict]:
    rng = random.Random(SEED)
    span_days = (END - START).days
    by_name = {p[0]: p for p in PLACES}
    cases = []
    for name, lat, lon, zone in PLACES:
        for _ in range(N_DATES):
            day = START + timedelta(days=rng.randrange(span_days + 1))
            cases.append({
                "place": name, "lat": round(lat, 1), "lon": round(lon, 1),
                "zone": zone, "date": day.strftime("%Y-%m-%d"),
            })
    for name, date in FIXED_CASES:
        _, lat, lon, zone = by_name[name]
        cases.append({
            "place": name, "lat": round(lat, 1), "lon": round(lon, 1),
            "zone": zone, "date": date,
        })
    # Per case: the impersonal ranking plus two seeded natal lagna signs.
    for c in cases:
        c["lagnas"] = [None, rng.randrange(12), rng.randrange(12)]
    return cases


def engine_windows(case: dict) -> dict | None:
    """The 16 slots with true-UTC boundary timestamps + midpoint lagna signs,
    Swiss-resolved (via crossval_window.engine_window) — the engine's inputs."""
    w = engine_window(case)
    if w is None:
        return None
    slots = []
    for half, end_of_half in (("day", w["sunset_ts"]), ("night", w["next_sunrise_ts"])):
        entries = w[half]
        for i, e in enumerate(entries):
            end_ts = entries[i + 1]["start_ts"] if i + 1 < len(entries) else end_of_half
            mid = (e["start_ts"] + end_ts) / 2
            asc = ascendant_sidereal(
                datetime.fromtimestamp(mid, UTC).replace(tzinfo=None),
                case["lat"], case["lon"],
            )
            slots.append({
                "name": e["name"],
                "start_ts": e["start_ts"],
                "end_ts": end_ts,
                "lagna_lon": asc.longitude,
                "lagna_sign": asc.sign_index,
            })
    kaal_starts = sorted(v["start_ts"] for v in w["kaals"].values())
    return {"slots": slots, "kaal_starts": kaal_starts}


def engine_rank(win: dict, purpose: str, lagna: int | None) -> dict:
    res = rank_windows(
        [(s["name"], s["start_ts"], s["end_ts"], s["lagna_sign"]) for s in win["slots"]],
        set(win["kaal_starts"]),
        purpose,
        natal_lagna_sign=lagna,
    )
    return {
        "personalisation": res["personalisation"],
        "candidates": [
            {"name": c.name, "start_ts": c.start, "end_ts": c.end,
             "lagna_sign": c.lagna_sign, "score": c.score, "personal": c.personal}
            for c in res["candidates"]
        ],
    }


def boundary_distance(lon: float) -> float:
    return min(lon % 30, 30 - lon % 30)


def worker_batch(payload: dict) -> list:
    proc = subprocess.run(
        ["node", "scripts/muhurat-batch.ts"],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        cwd=AURA_API,
        check=True,
    )
    return json.loads(proc.stdout)


def main() -> int:
    swe.set_ephe_path(str(ENGINE_ROOT / "ephe"))
    write_tables(export_tables())
    print(f"wrote {TABLES_PATH.relative_to(AURA_API.parent)}")

    cases = generate_cases()
    purposes = sorted(PURPOSES)
    print(f"cross-validating {len(cases)} (place, date) cases × {len(purposes)} "
          f"purposes × 3 lagna variants (seed={SEED}) ...")

    problems: list[str] = []
    golden_cases = []

    # Engine side, per case.
    engine_side = [(c, engine_windows(c)) for c in cases]

    # Worker layer 1: full end-to-end.
    full_payload = []
    for c, win in engine_side:
        if win is None:
            continue
        for purpose in purposes:
            for lagna in c["lagnas"]:
                full_payload.append({
                    "lat": c["lat"], "lon": c["lon"], "zone": c["zone"],
                    "date": c["date"], "purpose": purpose, "lagna": lagna,
                })
    act_full = worker_batch({"mode": "full", "cases": full_payload})

    # Worker layer 2: rank parity over the ENGINE's windows.
    rank_payload = []
    for c, win in engine_side:
        if win is None:
            continue
        for purpose in purposes:
            for lagna in c["lagnas"]:
                rank_payload.append({
                    "purpose": purpose, "lagna": lagna,
                    "windows": [
                        [s["name"], s["start_ts"], s["end_ts"], s["lagna_sign"]]
                        for s in win["slots"]
                    ],
                    "kaal_starts": win["kaal_starts"],
                })
    act_rank = worker_batch({"mode": "rank", "cases": rank_payload})

    i = 0
    n_boundary_windows = 0
    n_order_skipped = 0
    for c, win in engine_side:
        if win is None:
            problems.append(f"{c['place']} {c['date']}: engine found no rise/set")
            continue
        boundary_starts = {
            s["start_ts"] for s in win["slots"]
            if boundary_distance(s["lagna_lon"]) < BOUNDARY_DEG
        }
        n_boundary_windows += len(boundary_starts)
        case_rankings = []
        for purpose in purposes:
            for lagna in c["lagnas"]:
                tag = f"{c['place']} {c['date']} {purpose} lagna={lagna}"
                exp = engine_rank(win, purpose, lagna)
                full = act_full[i]
                parity = act_rank[i]
                i += 1

                # Layer 2 first: exact ranking parity on identical inputs.
                exp_cmp = {
                    "personalisation": exp["personalisation"],
                    "candidates": [
                        {k: v for k, v in cand.items()} for cand in exp["candidates"]
                    ],
                }
                if parity != exp_cmp:
                    problems.append(f"{tag}: RANK PARITY differs\n"
                                    f"  engine: {json.dumps(exp_cmp)}\n"
                                    f"  worker: {json.dumps(parity)}")
                    continue

                # Layer 1: end-to-end with input tolerance.
                if "error" in full:
                    problems.append(f"{tag}: worker refused ({full['error']})")
                    continue
                if full["personalisation"] != exp["personalisation"]:
                    problems.append(f"{tag}: personalisation "
                                    f"{full['personalisation']!r} != {exp['personalisation']!r}")
                exp_by_key = sorted(exp["candidates"], key=lambda x: x["start_ts"])
                act_by_key = sorted(full["candidates"], key=lambda x: x["start_ms"])
                if [x["name"] for x in exp_by_key] != [x["name"] for x in act_by_key]:
                    problems.append(f"{tag}: candidate sets differ — engine "
                                    f"{[x['name'] for x in exp_by_key]} vs worker "
                                    f"{[x['name'] for x in act_by_key]}")
                    continue
                clean = True
                for e, a in zip(exp_by_key, act_by_key, strict=True):
                    for ek, ak in (("start_ts", "start_ms"), ("end_ts", "end_ms")):
                        if abs(a[ak] / 1000 - e[ek]) > TOLERANCE_S:
                            problems.append(f"{tag}: {e['name']} {ek} differs by "
                                            f"{abs(a[ak] / 1000 - e[ek]):.1f}s")
                    if a["lagna_sign"] != e["lagna_sign"]:
                        eng_slot = next(s for s in win["slots"]
                                        if s["start_ts"] == e["start_ts"])
                        if boundary_distance(eng_slot["lagna_lon"]) < BOUNDARY_DEG:
                            clean = False  # contested at the tolerance, flagged
                        else:
                            problems.append(
                                f"{tag}: {e['name']} lagna sign {a['lagna_sign']} != "
                                f"{e['lagna_sign']} (engine asc "
                                f"{eng_slot['lagna_lon']:.3f}°, not near an ingress)")
                # Only a boundary slot that actually QUALIFIED for this ranking
                # can move its order; boundary slots outside the candidate set
                # are irrelevant to it.
                if any(x["start_ts"] in boundary_starts for x in exp["candidates"]):
                    clean = False
                if clean:
                    exp_order = [(x["name"], round(x["start_ts"], 3), x["score"])
                                 for x in exp["candidates"]]
                    act_order = [(x["name"], round(x["start_ms"] / 1000, 3), x["score"])
                                 for x in full["candidates"]]
                    if [(n, s) for n, _, s in exp_order] != [(n, s) for n, _, s in act_order]:
                        problems.append(f"{tag}: order/scores differ end-to-end — "
                                        f"engine {exp_order} vs worker {act_order}")
                else:
                    n_order_skipped += 1

                case_rankings.append({
                    "purpose": purpose, "lagna": lagna,
                    # Times rounded exactly as the golden's window inputs are,
                    # so the vitest rank-parity replay (which re-ranks those
                    # rounded windows) can compare deep-equal.
                    "expected": {
                        "personalisation": exp["personalisation"],
                        "candidates": [
                            {**cand,
                             "start_ts": round(cand["start_ts"], 3),
                             "end_ts": round(cand["end_ts"], 3)}
                            for cand in exp["candidates"]
                        ],
                    },
                })
        golden_cases.append({
            "place": c["place"], "lat": c["lat"], "lon": c["lon"],
            "zone": c["zone"], "date": c["date"],
            "windows": [
                {"name": s["name"], "start_ts": round(s["start_ts"], 3),
                 "end_ts": round(s["end_ts"], 3), "lagna_sign": s["lagna_sign"],
                 "boundary": boundary_distance(s["lagna_lon"]) < BOUNDARY_DEG}
                for s in win["slots"]
            ] if win else [],
            "kaal_starts": [round(t, 3) for t in win["kaal_starts"]] if win else [],
            "rankings": case_rankings,
        })

    print(f"boundary midpoints (asc within {BOUNDARY_DEG}° of an ingress): "
          f"{n_boundary_windows} slots; end-to-end order checks skipped on "
          f"{n_order_skipped} boundary-affected rankings (rank parity still exact)")

    if problems:
        print(f"\nFAILED — {len(problems)} disagreement(s):", file=sys.stderr)
        for p in problems[:25]:
            print(f"  {p}", file=sys.stderr)
        if len(problems) > 25:
            print(f"  ... and {len(problems) - 25} more", file=sys.stderr)
        return 1

    golden = {
        "tolerance_s": TOLERANCE_S,
        "boundary_deg": BOUNDARY_DEG,
        "descriptors": DESCRIPTORS,  # the gated corpus, byte-pinned for vitest
        "cases": golden_cases,
    }
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(json.dumps(golden, indent=None, separators=(",", ":")) + "\n")
    n_rankings = sum(len(c["rankings"]) for c in golden_cases)
    print(f"OK — wrote {GOLDEN_PATH.relative_to(AURA_API.parent)} "
          f"({len(golden_cases)} place-dates, {n_rankings} rankings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
