"""Generate the TRANSIT cross-validation golden for aura-api — the deploy gate.

aura-api composes the transit reading in-Worker (src/transit.ts) from
`transit_ingress` rows; engine/transits.py is the source of truth. This script
writes the golden the Worker's CI checks itself against.

WHAT THIS GOLDEN CARRIES THAT THE REPORT GOLDENS DO NOT: the INGRESS RUNS
themselves, as the input. The report goldens carry precomputed daily_guidance
rows because that is what the Worker reads; here the Worker reads ingress rows,
so the golden carries those and the vitest suite replays them without a
database. The runs are generated by the same `sign_runs` the seeder uses, so a
divergence between what the seeder writes and what the Worker expects would
show up here rather than in production.

`ingress_index` IS THE FIELD THAT MATTERS MOST. It is checked as an ABSOLUTE
value, not merely as a slope — the engine derives it by counting runs from
INGRESS_EPOCH and the Worker by counting table rows, and two implementations
that both advance by exactly 1 per ingress can still start from different
origins and select different copy forever. That is the week_index bug recorded
in docs/REPORTS.md, and an absolute-value golden is the only thing that catches
it.

CASE SELECTION is deliberate rather than uniform: all 12 Moon signs across a
span wide enough to exercise every weather class and every phase, PLUS the four
Sade Sati cases the audit measured as market-breaking (Sagittarius' detaching
episode, Virgo's recurring phases, Pisces' short dip, and an ordinary full
passage as a control). A golden that only sampled evenly would very likely miss
all four.

    uv run python scripts/crossval_transit.py
"""

from __future__ import annotations

import json
import os
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)))

from functools import lru_cache  # noqa: E402

import engine.transits as T  # noqa: E402
from engine.content import ACTIVE_REPORT_CONTENT_VERSION  # noqa: E402
from engine.reports import load_report_content_from_json  # noqa: E402
from engine.transits import (  # noqa: E402
    INGRESS_EPOCH,
    MOVERS,
    build_transit_reading,
    sign_runs,
)

# MEMOISE THE EPHEMERIS FOR THE DURATION OF THIS SCRIPT. Every call is a pure
# function of (body, instant), so caching changes no result — but the reading
# recomputes runs from scratch on every call (±4 years for the passages, ±12
# for the Sade Sati lookback), and 199 cases across 12 Moon signs re-ask for
# the same days millions of times. Uncached this script does not finish; cached
# it is a couple of minutes.
#
# Deliberately applied HERE and not in engine/transits.py: an unbounded cache
# inside the engine would be a memory leak in the nightly job for no benefit
# there, and the production path (the Worker) does no ephemeris at all — it
# reads the `transit_ingress` rows this script's `runs` block generates.
T.sidereal_positions = lru_cache(maxsize=None)(T.sidereal_positions)

ENGINE_ROOT = Path(__file__).resolve().parent.parent
GOLDEN_PATH = ENGINE_ROOT.parent / "aura-api" / "test" / "golden" / "transit_crossval.json"

#: The seeded span, matching db/migrate.py. The golden carries the whole run
#: table so the Worker's Sade Sati lookback has real data on both sides.
INGRESS_END = date(2045, 1, 1)

#: Even coverage: every Moon sign, sampled across six years.
SAMPLE_DATES = [date(2026, 1, 15) + timedelta(days=137 * i) for i in range(16)]

#: THE CASES THE AUDIT MEASURED. Each is a date chosen to land inside a
#: specific Sade Sati structure, so the golden proves the Worker reproduces
#: them and not merely that it agrees on ordinary dates.
SADE_SATI_CASES = [
    # (moon sign index, date, what it exercises)
    (8, date(2022, 10, 1), "Sagittarius: inside the DETACHED tail -> 'resuming'"),
    (8, date(2020, 6, 1), "Sagittarius: inside the full passage -> a phase key"),
    (11, date(2022, 6, 1), "Pisces: the 74-day dip -> 'brief', NOT the long passage"),
    (11, date(2026, 6, 1), "Pisces: the real passage"),
    (5, date(2039, 6, 1), "Virgo: inside the episode whose phases recur"),
    (9, date(2021, 6, 1), "Capricorn: an ordinary full passage, as a control"),
    (3, date(2026, 7, 21), "Cancer: no Sade Sati at all -> null block"),
]


def main() -> int:
    content = load_report_content_from_json(report_kind="transit")

    runs = []
    for body in MOVERS:
        for r in sign_runs(body, INGRESS_EPOCH, INGRESS_END):
            runs.append(
                {
                    "body": body,
                    "sign": r.sign,
                    "start_date": r.start.isoformat(),
                    "end_date": r.end.isoformat(),
                    "entry_retrograde": r.entry_retrograde,
                }
            )

    cases = []
    for on in SAMPLE_DATES:
        for ms in range(12):
            cases.append(
                {
                    "input": {"moon_sign": ms, "date": on.isoformat()},
                    "note": "even coverage",
                    "expected": build_transit_reading(ms, on, content),
                }
            )
    for ms, on, note in SADE_SATI_CASES:
        cases.append(
            {
                "input": {"moon_sign": ms, "date": on.isoformat()},
                "note": note,
                "expected": build_transit_reading(ms, on, content),
            }
        )

    golden = {
        "_about": (
            "Cross-validation golden for the TRANSIT reading. Generated by "
            "aura-engine (scripts/crossval_transit.py over engine/transits.py, "
            "the source of truth). Carries the ingress runs as input, because "
            "that is what the Worker reads — it links no ephemeris. "
            "`ingress_index` is checked as an ABSOLUTE value: the engine counts "
            "runs from INGRESS_EPOCH and the Worker counts table rows, and two "
            "implementations advancing by 1 per ingress from different origins "
            "would select different copy forever (the week_index bug). The last "
            "seven cases are the Sade Sati structures the audit measured. "
            "Regenerate whenever engine/transits.py or the corpus changes."
        ),
        "content_version": ACTIVE_REPORT_CONTENT_VERSION,
        "ingress_epoch": INGRESS_EPOCH.isoformat(),
        "ingress_end": INGRESS_END.isoformat(),
        "runs": runs,
        "cases": cases,
    }
    GOLDEN_PATH.write_text(json.dumps(golden, indent=1, ensure_ascii=False) + "\n")
    rel = GOLDEN_PATH.relative_to(ENGINE_ROOT.parent)
    print(
        f"golden file written: {rel} ({len(cases)} cases, {len(runs)} ingress runs, "
        f"{ACTIVE_REPORT_CONTENT_VERSION})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
